### ISSUE TITLE
Weird validation where field is an array

### ISSUE THREAD

**Issue by bluesd** [express-validator/express-validator#883] opened 2020-05-28 16:44 UTC
Request body
```
{  "field": [1,"a"] }
```

Validation rule:
```
body("field").isInt();
```
OR:
```
{  "field": [false,"a"] }
```
```
body("field").isBoolean();
```

Both examples validate without error. Doesn't matter the values are array, it seems to only check if the first element is valid. Is this expected behavior?
Should I append `.not().isArray()` to every chain?

express-validator: 6.4.0

**Comment by liqiang372** [comment] 2020-08-05 05:01
I can confirm that with version 6.6.0

when sending following request

```js
{
  a: [1, 'a'],
  b: 1,
  c: '1',
  d: '[1]',
  e: '[1, "a"]',
  f: false,
  g: 'false',
  h: '[false]',
  i: '[false, "a"]',
  j: [false, 'a'],
}
```

and add validation on these params, the result would be

```js
    body('a').isInt(), // valid
    body('b').isInt(), // valid
    body('c').isInt(), // valid
    body('d').isInt(), // invalid
    body('e').isInt(), // invalid

    body('f').isBoolean(), // valid
    body('g').isBoolean(), // valid
    body('h').isBoolean(), // invalid
    body('i').isBoolean(), // invalid
    body('j').isBoolean(), // valid
```
The cases like a and j are clearly wrong. Even though express-validator builds on top of validator.js, but since validator.js only checks string, there are some cases where a validator for params require more precise results.

For example

`isInt` should only check integer, if we need to check numerical like string, that should be a different method like `isNumerical` where it can check both number and numerical string.

similarly, `isBoolean` should only check `true` and `false`. if we want to check truthy value that it should be `isTruthy()` or `isFalsy()`

**Comment by liqiang372** [comment] 2020-08-05 05:21
@bluesd Your guess is correct. I think following is what causes current behavior,

at [this line](https://github.com/express-validator/express-validator/blob/master/src/context-items/standard-validation.ts#L16), the value is converted to string. And in the [toString](https://github.com/express-validator/express-validator/blob/master/src/utils.ts#L15),
if value is array, then take the first element and stringify it. 
What do you think @gustavohenke

**Comment by fedeci** [comment] 2020-12-27 16:23
Partially related to #931, closing this.
/cc @gustavohenke

**Closed by fedeci** 2020-12-27 16:23 UTC
