### ISSUE TITLE
multiple custom in schema

### ISSUE THREAD

**Issue by SteveYip** [express-validator/express-validator#690] opened 2019-02-21 08:51 UTC
I am unable to set the multiple custom function in schema. For example, i try to validate parm is invalid date and is before some date. both of them have own error message. How can i make two custom function for checking valid data and  parma is before some date

**Comment by gustavohenke** [comment] 2019-02-26 01:13
It isn't supported yet!

**Comment by gustavohenke** [comment] 2019-02-26 01:13
Duplicate of #552

**Closed by gustavohenke** 2019-02-26 01:13 UTC
