### ISSUE TITLE
Running validations imperatively

### ISSUE THREAD

**Issue by castri1** [express-validator/express-validator#731] opened 2019-06-27 13:08 UTC
I followed the example below to create a validation middleware using a validation chain:

**example:**

```javascript
// can be reused by many routes
const validate = async validations => {
  return (req, res, next) => {
    await Promise.all(validations.map(validation => validation.run(req)));

    const errors = validationResult(req);
    if (errors.isEmpty()) {
      return next();
    }

    res.status(422).json({ errors: errors.array() });
  };
};

app.post('/api/create-user', validate([
  body('email').isEmail(),
  body('password').isLength({ min: 6 })
]), async (req, res, next) => {
  // request is guaranteed to not have any validation errors.
  const user = await User.create({ ... });
});
```

**my code** (using typescript):
`/models/order.ts`
```typescript
// order validation chain
import { checkSchema, ValidationChain } from 'express-validator';

export const schema: ValidationChain[] = checkSchema({
 orderNumber: {
    isString: true,
    errorMessage: 'Order number is required'
  }
});
```

```typescript
import { ValidationChain, validationResult } from 'express-validator';
import { Router, Request, Response, NextFunction } from 'express';

import * as orderModel from '../models/order';

const router = Router();

type RouteHandler = (
  req: Request,
  res: Response,
  next: NextFunction
) => Promise<void>;

// validation middleware
const validate = (validations: ValidationChain[]): RouteHandler => {
  return async (
    request: Request,
    response: Response,
    next: NextFunction
  ): Promise<void> => {
    await Promise.all(
      validations.map(
        (val: ValidationChain): Promise<Context> => val.run(request)
      )
    );

    const result = validationResult(request);

   // result.isEmpty() is always true
    if (!result.isEmpty()) {
      response.status(422).json();
      return;
    }
    next();
  };
};

// route handler using the validation middleware
router.post('/', validate(orderModel.schema), ordersController.createOrder);
```

The issue is that when awaiting for all the validations in:

```typescript
await Promise.all(
      validations.map(
        (val: ValidationChain): Promise<Context> => val.run(request)
      )
    );
```
The request object is not being affected and then when using `const result = validationResult(request);` No errors are attached to the object. In other words, result.isEmpty() is always true.

I modified the code a little bit just to see what all the promises resolved:

```typescript
const data = await Promise.all(
      validations.map(
        (val: ValidationChain): Promise<Context> => val.run(request)
      )
    );
```
And all the errors are inside the data variable. To be specific data is an array of Context objects, and those objects are holding the errors. The issue is that when running validations imperatively the request object is not being affected.

Im using express-validator version *6.0.1*

Thanks for your help.

**Comment by gustavohenke** [comment] 2019-06-27 21:00
Yup, this was reported already and will be fixed with the new version coming shortly!

**Comment by gustavohenke** [comment] 2019-06-27 21:00
Duplicate of #728

**Closed by gustavohenke** 2019-06-27 21:00 UTC

**Comment by gustavohenke** [comment] 2019-06-27 21:29
👋 this has been published to [`v6.1.0`](https://github.com/express-validator/express-validator/releases/tag/v6.1.0) 🚢

**Comment by krzysztof-o** [comment] 2019-06-28 08:16
I confirm the fix is working for me 👍

**Comment by castri1** [comment] 2019-06-28 13:13
For me too!!! Thanks!!!
