### ISSUE TITLE
Validation API features equals, isNumber, isISO8601 are missing/not documented...

### ISSUE THREAD

**Issue by leor491** [express-validator/express-validator#643] opened 2018-09-21 21:10 UTC
In the new validation api, there is either no documentation or feature to check for numbers, integers, dates, ID or equals.  For example (https://stackoverflow.com/questions/37585434/express-validator-validation-schema-with-equals-property) how to check that 2 password fields are equal outside if the legacy api?

**Comment by dsvoid** [comment] 2018-09-23 18:49
@leor491 I thought this was a problem as well, but I'm not 100% sure if it's the maintainer's job to handle this, since this is a middleware that just wraps around validator.js.

https://github.com/chriso/validator.js has the full list of validators.

**Comment by gustavohenke** [comment] 2018-09-26 11:54
Duplicate of #590

**Comment by leor491** [comment] 2018-09-26 17:44
I have no problem with this thread being considered a duplicate, as long as I can get the word out.  Also, please add "isIn" and "normalizeMail" to the list.  THANKS!

**Comment by leor491** [comment] 2018-09-26 17:57
> @leor491 I thought this was a problem as well, but I'm not 100% sure if it's the maintainer's job to handle this, since this is a middleware that just wraps around validator.js.
> 
> https://github.com/chriso/validator.js has the full list of validators.

Yes, that is a drawback of wrapping.  There should still be a way to get those features.

  

> Duplicate of #590

I am now not concerned with the documentation but also the features that are available.  Can we add "isIn" and "normalizeEmail" to the list?  Thanks!

**Comment by leor491** [comment] 2018-09-26 18:19
All validation features seem to be available in validator, however "equals" only seems to function in the legacy API's as mentioned earlier. i.e.

`[body("password", "Passwords must match.").equals("password2")]`

which always fails.

**Comment by gustavohenke** [comment] 2018-10-01 08:56
@leor491 `equals` expects the value of `password` **to be** `password2` in this case. If that's documented somewhere, that's a mistake and should be removed from the docs.
Please check this example instead: https://express-validator.github.io/docs/custom-validators-sanitizers.html#example-checking-if-password-confirmation-matches-password

**Comment by boompig** [comment] 2019-05-14 23:31
Hi, I may be a bit late to this post, but the documentation should at least have a link to https://github.com/chriso/validator.js#validators for a complete list of validators. Otherwise the user's path to discovery is:

1. search the docs, nothing there
2. google a little
3. find this GitHub issue and find the link mentioned above
4. follow that link

It would be very easy to add the link to the docs. Thank you to the maintainer for this amazing library 😄

**Closed** 2019-05-22 06:01 UTC
