### ISSUE TITLE
Conditional Checks

### ISSUE THREAD

**Issue by formatically** [express-validator/express-validator#655] opened 2018-11-13 15:12 UTC
I am hoping someone can help me out.  I've seen this same question asked before, but the answers are not using the latest version of express-validator. 

In short, I am trying to make a param only required if another param is equal to a specific value. 

For example,

membershipType can be "paid", or "free".
`check("membershipType").isIn(['paid','free'])`

`If membershipType === "paid", then check("amount").isDecimal().isLength({min:2})`

How do I make that conditional check? 

Thanks!

**Comment by gustavohenke** [comment] 2018-11-20 13:06
Duplicate of #439

**Closed by gustavohenke** 2018-11-20 13:06 UTC

**Comment by gustavohenke** [comment] 2019-06-27 21:29
👋 this has been published to [`v6.1.0`](https://github.com/express-validator/express-validator/releases/tag/v6.1.0) 🚢
