### ISSUE TITLE
checkNoUnknown()

### ISSUE THREAD

**Issue by CarlosRodar** [express-validator/express-validator#927] opened 2020-09-17 23:44 UTC
So I would like to add this to the v4+ APIs, not to the legacy APIs as they are difficult to implement, modularise and type.

My API suggestion for now is:

```js
app.get('/some/path', [
  check('something').not().isEmpty(),
  checkNoUnknown()
], (req, res, next) => {});
```

Any better names? 🤔

_Originally posted by @gustavohenke in https://github.com/express-validator/express-validator/issues/266#issuecomment-359225100_

Did you added this feature for the library?

**Comment by geritol** [comment] 2020-10-15 12:54
Would love to see something like this if there is a possibility for it!

**Comment by gustavohenke** [comment] 2020-12-11 11:05
Duplicate of #266 and #578

**Comment by alexandernanberg** [comment] 2021-03-23 08:08
I'm using a schema but this seems to work quite well

```ts
const schema: Schema = {
  avatar: {
    in: ['body'],
    isURL: true,
    optional: { options: { nullable: true } },
  },
};

const schemaKeys = Object.keys(schema);

await checkSchema({
  ...schema,
  '*': {
    in: ['body'],
    custom: {
      options: (field, { path }) => {
        if (!schemaKeys.includes(path)) {
          throw new Error(`Unknown field: ${path}`);
        }
        return true;
      },
    },
  },
}).run(req);
```

**Comment by gustavohenke** [comment] 2023-02-18 11:13
This is coming to v7 🙂

**Comment by gustavohenke** [comment] 2023-04-15 09:36
Hi hi, https://github.com/express-validator/express-validator/releases/tag/v7.0.0 is out with a fix for this 🙂

**Closed by gustavohenke** 2023-04-15 09:36 UTC
Labels: i: enhancement, duplicate
