### ISSUE TITLE
Integration with Swagger

### ISSUE THREAD

**Issue by Sl4yZ** [express-validator/express-validator#1186] opened 2022-11-12 15:36 UTC
Hello,

Is there any way to link the validation methods of my routes to swagger ?

**Comment by gustavohenke** [comment] 2023-04-13 06:19
Hello!
Nothing built into express-validator, no.

I'd be happy to accept PRs implementing this, though.

**Comment by gustavohenke** [comment] 2023-04-13 06:21
Duplicate of #923

**Closed by gustavohenke** 2023-04-13 06:21 UTC
Labels: i: enhancement
