### ISSUE TITLE
validation-result.d.ts:13:64 - error TS1005: ',' expected. error

### ISSUE THREAD

**Issue by achmadfatoni** [express-validator/express-validator#891] opened 2020-07-03 09:45 UTC
i use express with typescript, got error during compilation 

```
node_modules/express-validator/src/validation-result.d.ts:13:64 - error TS1005: ',' expected.

13     constructor(formatter: ErrorFormatter<T>, errors: readonly ValidationError[]);
                                                                  ~~~~~~~~~~~~~~~

node_modules/express-validator/src/validation-result.d.ts:13:79 - error TS1005: ',' expected.

13     constructor(formatter: ErrorFormatter<T>, errors: readonly ValidationError[]);
 ```

**Comment by asarycx** [comment] 2020-07-22 05:35
Bump ⬆

**Comment by asarycx** [comment] 2020-07-22 06:09
try using node.js require instead of ES import

❌`import { body, check } from "express-validator";`
✔`const {  body, check } = require("express-validator");`

**Comment by liqiang372** [comment] 2020-07-29 01:22
I don't seem to have luck to reproduce it, can you help create a minimal reproducible repo?

**Comment by glvb** [comment] 2020-10-03 02:01
I am seeing this same issue when building on heroku but I'm unable to reproduce locally.

**Comment by achmadfatoni** [comment] 2020-10-04 13:21
in one of my project i got this kind of errors but in another project working fine.

note: I do import in the same way, I do check package.lock I use same exact version.

**Comment by glvb** [comment] 2020-10-04 14:11
Do your tsconfig.json files differ between the projects?

**Comment by achmadfatoni** [comment] 2020-10-20 16:12
@glvb i have same exact tsconfig file
```
{
  "compilerOptions": {
    "outDir": "./build",
    "allowJs": true,
    "target": "es5",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*.ts"]
}

```

**Comment by AsachAtikin** [comment] 2020-10-27 07:08
Try to update typescript to 4 version
```
"devDependencies": {,
  "typescript": "4.0.5"
},
```

**Comment by gustavohenke** [comment] 2020-12-11 11:01
Huh, that shouldn't be needed @AsachAtikin... 
We currently compile on TS 3.9.7:
https://github.com/express-validator/express-validator/blob/2b715a83353a6659b6d37ddf23df343a5b6fb19f/package.json#L61

which version were you using before?

**Comment by gustavohenke** [comment] 2022-09-25 00:47
Closing, but please open a new issue with a reproducible repo if possible. Thanks!

**Closed by gustavohenke** 2022-09-25 00:47 UTC
Labels: typescript
