### ISSUE TITLE
Is it possible to only allow only certain values to be set on the request body when using a schema?

### ISSUE THREAD

**Issue by marnixhoh** [express-validator/express-validator#832] opened 2020-02-12 10:03 UTC
I have a an endpoint that accepts two values:
body.valueOne
body.valueTwo

Is it possible to check using a schema that no other values are set on the body besides these two. In other words, a body with the following values should throw an error:
body.valueOne
body.valueTwo
body.valueThree

Thanks in advance!

**Comment by gustavohenke** [comment] 2020-02-12 21:20
Duplicate of #809

**Comment by gustavohenke** [comment] 2020-02-12 21:20
Duplicate of #746

**Comment by gustavohenke** [comment] 2020-02-12 21:21
Short answer: not really, but you can use `matchedData` to avoid saving more data than you wish in your database, for example. Look at those duplicates.

**Closed by gustavohenke** 2020-02-12 21:21 UTC

**Comment by marnixhoh** [comment] 2020-02-17 07:48
Thanks for your replies.
Question regarding the solution as posted in #809: is it possible to use matchedData() in a schema somehow? It would be nice to have matchedData() be part of the schema so that the schema can check for optionals.
