### ISSUE TITLE
I want to set a rule that the user cant send a field other than the fields that I set to send to the server.

### ISSUE THREAD

**Issue by behzadnm99** [express-validator/express-validator#746] opened 2019-07-22 13:15 UTC
I want to set a rule that the user cant send a field other than the fields that I set to send to the server. i want that user send only send this fields : {name: String, city: String}. no OTHER fields.

please help me to do this with express-validator

**Comment by gustavohenke** [comment] 2019-07-29 22:01
This has been asked before: #266, and it is not something supported by express-validator yet.

Since then I haven't spent much time thinking about this. I welcome any ideas.

**Comment by gustavohenke** [comment] 2019-07-29 22:12
Also, if you use [`matchedData()`](https://express-validator.github.io/docs/matched-data-api.html), you can pretty much solve the problem of getting more than you expect.

**Comment by gustavohenke** [comment] 2020-02-12 21:20
Duplicate of #809

**Closed** 2022-09-25 08:53 UTC
Labels: duplicate
