### ISSUE TITLE
`toBoolean` always returning string value instead of boolean value

### ISSUE THREAD

**Issue by GSpletty** [express-validator/express-validator#1075] opened 2021-08-05 13:56 UTC
## Describe the bug

In a recent build we found out that a boolean value in the request query was always being interpreted as true.

## To Reproduce

For express-validator ^6.6.0, when calling `toBoolean()` in the validation chain (either schema validation or direct request level validation), the returned value for `'false'` is still the string of `'false'`, not the boolean `false`.

For example
```typescript
app.get('/test',
  query('bool').toBoolean(),
  validate,
  async (req, res) => {
      console.log(req.query.bool);
      console.log(typeof req.query.bool);
  });
```
With `localhost:8090/test?bool=false` this logs:
```
false
string
```

NOTE: The `validate` middleware throws any errors if the validation chain reported any errors.

## Expected behavior

The above example should log:
```
false
boolean
```

## Current behavior

With the expected boolean values being strings instead, we see they are always being interpreted as true.

## Express-validator version:

- Version: 6.6.0

**Comment by GSpletty** [comment] 2021-08-05 18:35
After additional testing, when adding `body(bool).toBoolean()` and testing that method, it correctly gets cast to a Boolean type versus a string.
Example body:
```json
{
  "bool": false
}
```

**Comment by fedeci** [comment] 2021-08-07 14:29
I cannot reproduce the bug locally, can you create a reproduction repo, please?

**Comment by GSpletty** [comment] 2021-08-09 18:48
Sadly I cannot share the source repo, and when trying to build a new project from scratch, it works as expected. So it must be something with our project. It worked fine until one new build (with no new package changes) where it broke.

**Comment by fedeci** [comment] 2021-08-09 21:54
Closing this for the moment. Let me know if you could fix it.

**Closed by fedeci** 2021-08-09 21:54 UTC
Labels: i: bug

**Comment by GSpletty** [comment] 2021-08-17 16:11
An update on this, we think this might be a problem with the underlying `validator` dependency. We had switched to calling `toBoolean` after the schema validation right in the function calls and noticed this was sometimes still an issue on `validator` 13.6, but when using `validator` 13.1.1, we do not notice the issue.

**Comment by fedeci** [comment] 2021-08-17 23:19
Are you on `express v5`?

**Comment by GSpletty** [comment] 2021-08-18 17:52
We did recently upgrade to `express v5` to adopt the more native async error handling!

**Comment by fedeci** [comment] 2021-08-18 18:01
That's the problem, `query` is now just a getter of some `url` properties. We cannot mutate it case it does not have any value.
