### ISSUE TITLE
conditional oneOf validators

### ISSUE THREAD

**Issue by bgrgndzz** [express-validator/express-validator#629] opened 2018-08-21 01:38 UTC
For the project I'm working on currently, I need to validate an unusual form. The form lets you choose two sides, and presents you with two different forms. If you select side-1, the form-1 fields will all be required, and vice versa, but I can't seem to achieve this with express-validator.

What I'm trying to achieve is to check a boolean in request body, and if it's true, use one set of validators, if it's false, use another set of validators. For this purpose, I think a "conditional validator" is needed. I propose an optional condition argument added to the oneOf validator, but creating another validator method works too.

**Comment by formatically** [comment] 2018-11-14 02:54
Did you find a solution? I am trying to do the same thing.

**Comment by gustavohenke** [comment] 2018-11-20 13:05
Duplicate of #439

**Closed by gustavohenke** 2018-11-20 13:05 UTC
