### ISSUE TITLE
req.getValidationResult should return result of custom validation

### ISSUE THREAD

**Issue by thatshailesh** [express-validator/express-validator#639] opened 2018-09-13 07:29 UTC
Right now the result format of `req.getValidationResult()` is this
```
 { isEmpty: [Function],
  array: [Function],
  mapped: [Function],
  formatWith: [Function],
  throw: [Function] }
```

if I do `param('userId').exists().isMongoId().custom(val => UserSchema.isValid(val))`

where `isValid()` is: 

```
UserSchema.statics = {
  isValid(id) {
		return this.findById(id)
			.then(result => {
				if (!result) throw new Error('Not a valid account')
			})
	}
}
```
As you can see if account is valid I need to find again in my controller even if i return `result` from custom `isValid()` function

@ctavan @gustavohenke  any solution or is it possible to include in API ?

**Comment by gustavohenke** [comment] 2018-09-14 00:00
Hi @thatshailesh,
So a few things to keep in mind here:
- You seem to be setting your validations using the new API (`param(...)`, called the check API. Please don't mix if with the legacy one (`req.getValidationResult()`). [Use `validationResult(req)` instead](https://express-validator.github.io/docs/check-api.html#validationresultreq).
- Depending on the express-validator version you are running (<5.3.0), you are likely suffering from a bug where not returning a truthy value from the promise means a validation failure (see #593)

What the problem is is not clear to me, so please check your version and migrate your validation result function, and let me know if you still face it, adding as much details as you can.

**Comment by thatshailesh** [comment] 2018-09-14 05:37
Hi thanks for your response 

I am using `v5.3.0`, and tried new `validationResult(req)` also and its also giving me result in this format

```
 { isEmpty: [Function],
  array: [Function],
  mapped: [Function],
  formatWith: [Function],
  throw: [Function] }
```

so what I want is if I use custom validation like `.custom(val => someAsyncAPI(val))`

and if there is no error from that `someAsyncAPI` i want to return actual data not `truthy` value

Example: 
```
function someAsyncAPI(val) {
  return UserSchema.findById(val)
  .then(result => {
    if (!result) throw new Error('Data not found')
    return result
  })
}
```
As you can see I want to return the result if it's found in the database but where to find that in the response of `validationResult(req)`?

I hope it helps, please let me know if it's not clear

**Comment by gustavohenke** [comment] 2018-09-14 14:10
You should discover which of those methods suits you better.
Have a look here: https://express-validator.github.io/docs/validation-result-api.html

As it stands, you don't seem to have a bug or feature request to report, so I'll close the issue, but feel free to ask other things!

**Closed by gustavohenke** 2018-09-14 14:10 UTC
