### ISSUE TITLE
It is possible to throw error when non declared params are send in a request?

### ISSUE THREAD

**Issue by TheLox95** [express-validator/express-validator#612] opened 2018-07-19 21:18 UTC
Let say I have this schema
```javascript
router.post('/create', checkSchema({
    user_name: {
        in: ['body'],
        errorMessage: 'username required',
        exists: true,
    },
    password: {
        in: ['body'],
        errorMessage: 'required and should be 8 characters contains number and letter',
        exists: true,
    },
}), middlewares.create(create));
```
I would like to know if there is a option to not allow any other param besides these and show an error

**Comment by gustavohenke** [comment] 2018-07-20 12:04
Duplicate of #558

**Closed by gustavohenke** 2018-07-20 12:04 UTC

**Comment by gustavohenke** [comment] 2023-04-15 09:39
Hi hi, https://github.com/express-validator/express-validator/releases/tag/v7.0.0 is out with a fix 🙂
