### ISSUE TITLE
Option to stop cascade validation on first fail for performance purpose 

### ISSUE THREAD

**Issue by singno** [express-validator/express-validator#696] opened 2019-03-29 09:26 UTC
Consider this example:
```
const { check } = require('express-validator/check');

app.post('/user', [
check('password').custom((value, { req }) => {
    if (value !== req.body.passwordConfirmation) {
      throw new Error('Password confirmation is incorrect');
    }
  }),
  check('email').custom(value => {
    return User.findByEmail(value).then(user => {
      if (user) {
        return Promise.reject('E-mail already in use');
      }
    });
  })
], (req, res) => {
  // Handle the request somehow
});
```
I don't want the `check('email')` execute when check('password') has already fails.

**Comment by gustavohenke** [comment] 2019-04-24 03:23
Duplicate of #638

**Closed** 2019-04-24 03:23 UTC
