### ISSUE TITLE
express-validator with multer

### ISSUE THREAD

**Issue by agustinl** [express-validator/express-validator#719] opened 2019-06-04 04:50 UTC
Hi all,

Referring to this [issue ](https://github.com/expressjs/multer/issues/661) in multer, maybe it would be helpful if this is clarified somewhere in the guide.

> That means that you have to run the validation after Multer...

This also happens with this validator. The value (titulo or descripcion in this case) return `undefined` in value parameter and never perform the validation.

![image](https://user-images.githubusercontent.com/6640773/58851557-9b7f2580-8669-11e9-87bd-21a71294d25a.png)

![image](https://user-images.githubusercontent.com/6640773/58851427-1dbb1a00-8669-11e9-9dcc-ef7e999817f2.png)

But if multer run before the validation, it works.

![image](https://user-images.githubusercontent.com/6640773/58851541-8b674600-8669-11e9-8c99-4f6049045755.png)

![image](https://user-images.githubusercontent.com/6640773/58851476-4cd18b80-8669-11e9-8708-9f36a07242a8.png)

A small contribution after searching for hours what happened haha

Regards, and thanks for the validator! ❤️

**Comment by gustavohenke** [comment] 2022-09-25 00:49
Duplicate of #783

**Closed by gustavohenke** 2022-09-25 00:49 UTC
Labels: duplicate
