### ISSUE TITLE
An array in the querystring can (by)pass the validation if the first element is correct, but useless when expecting a single value.

### ISSUE THREAD

**Issue by darkman82** [express-validator/express-validator#755] opened 2019-08-06 16:19 UTC
Hi guys,

Let's suppose we had a GET like that http://localhost:3000/test?type=new&type=foo
```
// Ver 6.1.1
router.get('/',
    v.query('type').isIn(['new','renewal','upgrade'])
    function (req, res) {
        const errors = v.validationResult(req);
        if (!errors.isEmpty())
             return res.status(422).json({errors: errors.array()});
        return res.status(200).json(req.matchedData);
    }
);
// Result: {"type":["new","foo"]}
// Expected: Validation failure (or sanitization)
```
It seems that this isn't a desired behavior as this would force us to do a further sanitization in order to consume the single parameter instead of the array. 
Is that correct?

Thank you

**Comment by gustavohenke** [comment] 2019-08-20 07:22
Duplicate of #704

**Comment by darkman82** [comment] 2019-08-20 08:02
As a workaround we had to use not().isArray() for all fields or sanitization, eg:

```
v.query('currency').optional().not().isArray().isIn(['EUR','GBP','USD'])
// toInt() it's enough for numeric values
v.query('months').isIn(['1','3','6','12']).toInt(),
```

**Comment by fedeci** [comment] 2021-02-01 22:13
Also related to #791

**Comment by gustavohenke** [comment] 2023-04-15 09:45
Hi hi, https://github.com/express-validator/express-validator/releases/tag/v7.0.0 is out with a fix for this 🙂

**Closed by gustavohenke** 2023-04-15 09:45 UTC
Labels: help wanted
